### PR TITLE
Use GAMA 1.8.2 alpha

### PR DESCRIPTION
**Pull request by ndgnuh**
For #48

- [x] Travis
- [x] Github Action
- [x] Continous release
- [x] Stable release

### CODE REVIEW

**Comment by ndgnuh** [comment]
I think I'm done, but I don't know how to get the tag to pass it to the release action though, I guess that the one who make the release must bump the version number themselves.

**Comment by RoiArthurB** [comment]
1. You can delete the file `.travis.yml`, we're switching from Travis to GHA, so this file is no longer required
2. Nice better regex than my old one for gathering GAMA :+1:

**Review by RoiArthurB — CHANGES_REQUESTED** [review]
Remove `.travis.yml` file

**Comment by ndgnuh** [comment]
Done, I actually delete it from the web GUI. :laughing:

**Review by RoiArthurB — APPROVED** [review]

**Pull request merged**
